# Use an Ubuntu base image
#Build this docker on a mac M1/M2 with:
#docker buildx build --platform linux/amd64 -t new_influensa_pipline_v1 .
# RUN - 
FROM ubuntu:20.04

# Set environment variables for non-interactive installation
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y wget openjdk-11-jre-headless bash python3 python3-pip git build-essential zlib1g-dev libncurses5-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev cmake

RUN apt-get update && \
    apt-get install -y --fix-missing unzip

# Install Python packages
#RUN pip3 install pandas matplotlib seaborn biopython pysam

# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh && \
    bash Miniconda3-py39_4.10.3-Linux-x86_64.sh -b -p /miniconda && \
    rm Miniconda3-py39_4.10.3-Linux-x86_64.sh
ENV PATH="/miniconda/bin:${PATH}"
RUN conda update -y conda

# Install Python packages
RUN conda install -y -c conda-forge pandas matplotlib seaborn biopython=1.81
RUN conda install -y -c bioconda pysam

# Install nanoplot
RUN conda install -c bioconda nanoplot

# Install chopper
RUN wget https://github.com/wdecoster/chopper/releases/download/v0.5.0/chopper-linux.zip \
    && unzip chopper-linux.zip -d /usr/local/bin/ \
    && chmod +x /usr/local/bin/chopper




# Set the working directory
WORKDIR /app

# Copy the script and reference files into the container
COPY script_files /app/script_files
COPY references /app/references
COPY dataset /app/dataset
#COPY results /app/results


# Make the script executable
#RUN chmod +x /app/script_files/master_NF.sh 

# Set the default command to run the script
#CMD ["/app/script_files/master_NF.sh"]

